- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo # repo file is existing here only.
    dest: /etc/yum.repos.d/mongo.repo # File will copy to that location

- name: install mongodb server
  ansible.builtin.package:
    name: mongodb-org
    state: present
    
- name: allow remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1' # regexp means which one we need to replace
    replace: '0.0.0.0'

- name: start and enable the service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes