MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/mysql/mysql_root_password', region='us-east-1', decrypt=True ) }}"


#This is instead of vault we can use AWS service SYSTEMS MANAGER --> PARAMETER STORE there we can maintain passwords.
# Like above we can assign password to the variable.