- name: daemon reload. 
  # systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

# Handlers are notifiers when there is change in particular task we can notify other task if there is no change no need to run